version: '3.8'
services:
  vue_ui:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '$VUE_HOST_PORT:$VUE_CONTAINER_PORT'
    container_name: vue_ui
    volumes:
       - './:/usr/src/nlcntt'
       - 'vue_ui:/usr/src/nlcntt/node_modules'
    networks:
      - nlcntt-network
networks:
  nlcntt-network:
    name: nlcntt-network
    driver: bridge
    # external: true
volumes:
  vue_ui: