version: '3.8'
services:
  vue_ui:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '$VUE_HOST_PORT:$VUE_CONTAINER_PORT'
    container_name: vue_ui
    volumes:
       - './:/usr/src/nlcntt'
       - '/usr/src/nlcntt/node_modules'
volumes:
  vue_ui:
    external: false